"""reinit with StudyProgram

Revision ID: 8e95c4625a13
Revises: 
Create Date: 2025-05-31 18:46:00.126863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e95c4625a13'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_programs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('study_program_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['study_program_id'], ['study_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('study_program_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['study_program_id'], ['study_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('telegram_channel_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deadlines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_option_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_option_id'], ['group_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_option_id'], ['group_options.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deadline_id', sa.Integer(), nullable=False),
    sa.Column('offset', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deadline_id'], ['deadlines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deadline_id', 'offset')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('user_subscriptions')
    op.drop_table('deadlines')
    op.drop_table('group_options')
    op.drop_table('users')
    op.drop_table('groups')
    op.drop_table('study_programs')
    # ### end Alembic commands ###
